// Code generated by Kitex v0.4.3. DO NOT EDIT.

package paymentservice

import (
	server "github.com/cloudwego/kitex/server"
	da "github.com/weedge/craftsman/cloudwego/common/kitex_gen/payment/da"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler da.PaymentService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
