// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AssetChangeHandler is an autogenerated mock type for the AssetChangeHandler type
type AssetChangeHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: oldAssetCn
func (_m *AssetChangeHandler) Execute(oldAssetCn int64) int64 {
	ret := _m.Called(oldAssetCn)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(oldAssetCn)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

type mockConstructorTestingTNewAssetChangeHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAssetChangeHandler creates a new instance of AssetChangeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAssetChangeHandler(t mockConstructorTestingTNewAssetChangeHandler) *AssetChangeHandler {
	mock := &AssetChangeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
