// Code generated by Kitex v0.4.3. DO NOT EDIT.

package paymentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	station "github.com/weedge/craftsman/cloudwego/common/kitex_gen/payment/station"
)

func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

var paymentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*station.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ChangeAsset": kitex.NewMethodInfo(changeAssetHandler, newPaymentServiceChangeAssetArgs, newPaymentServiceChangeAssetResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "station",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.3",
		Extra:           extra,
	}
	return svcInfo
}

func changeAssetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*station.PaymentServiceChangeAssetArgs)
	realResult := result.(*station.PaymentServiceChangeAssetResult)
	success, err := handler.(station.PaymentService).ChangeAsset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceChangeAssetArgs() interface{} {
	return station.NewPaymentServiceChangeAssetArgs()
}

func newPaymentServiceChangeAssetResult() interface{} {
	return station.NewPaymentServiceChangeAssetResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ChangeAsset(ctx context.Context, req *station.BizAssetChangesReq) (r *station.BizAssetChangesResp, err error) {
	var _args station.PaymentServiceChangeAssetArgs
	_args.Req = req
	var _result station.PaymentServiceChangeAssetResult
	if err = p.c.Call(ctx, "ChangeAsset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
