// Code generated by Kitex v0.4.3. DO NOT EDIT.
package paymentservice

import (
	server "github.com/cloudwego/kitex/server"
	station "github.com/weedge/craftsman/cloudwego/common/kitex_gen/payment/station"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler station.PaymentService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
