apiVersion: apps/v1
kind: Deployment # mentions this is a Deployment
metadata:
  name: ai-creator-deployment # name of Deployment
  namespace: doraemon
spec:
  replicas: 2 # creates 2 replicated Pods
  selector:
    matchLabels:
      app: ai-creator # defines how the Deployment finds which Pods to manage
  template:
    metadata:
      labels:
        app: ai-creator # specifies that the Pods are to be named as ai-creator
    spec: # specification for each Pod .This block indicates that the Pods run one container 'ai-creator-container', which runs the weedge/ai-creator dockerhub image .
      containers:
        - name: ai-creator-container # name of the container running inside the Pod
          image: weedge/ai-creator # image to deployed in the container
          #imagePullPolicy: Always # pull image from the repository (dockerhub) always
          imagePullPolicy: Never
          #imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8123 # run on port 8123
          livenessProbe: # To check the health of the Pod
            httpGet:
              path: /health
              port: 8123
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 8123
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env: # list of env variables passed to the app
            - name: REDIS_TYPE
              valueFrom:
                configMapKeyRef:
                  name: ai-creator-configmap
                  key: redis-type
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: ai-creator-configmap
                  key: redis-service
            - name: TEMPLATE_DIR
              valueFrom:
                configMapKeyRef:
                  name: ai-creator-configmap
                  key: template-dir

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-creator-secret
                  key: redis-password
            - name: NOLIBOX_API_SK
              valueFrom:
                secretKeyRef:
                  name: ai-creator-secret
                  key: nolibox-api-sk
            - name: NOLIBOX_API_AK
              valueFrom:
                secretKeyRef:
                  name: ai-creator-secret
                  key: nolibox-api-ak
---
kind: Service # mentions this is a service
apiVersion: v1
metadata:
  name: ai-creator-service # name of service
  namespace: doraemon
spec:
  type: NodePort # service type to be NodePort
  ports:
    - name: http
      port: 80 # serve on port 80
      targetPort: 8123 # reach to port 8123 of all the Pods in the selector block
      nodePort: 30000 # use port 30000 as nodePort

  selector:
    app: ai-creator # The set of Pods with name'ai-creator' is targeted by this Service

