// Code generated by thriftgo (0.2.3). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Err int64

const (
	Err_GateWayBadRequest     Err = 100000
	Err_InteractionBadRequest Err = 10000
	Err_PaymentBadRequest     Err = 20000
	Err_IMBadRequest          Err = 30000
)

func (p Err) String() string {
	switch p {
	case Err_GateWayBadRequest:
		return "GateWayBadRequest"
	case Err_InteractionBadRequest:
		return "InteractionBadRequest"
	case Err_PaymentBadRequest:
		return "PaymentBadRequest"
	case Err_IMBadRequest:
		return "IMBadRequest"
	}
	return "<UNSET>"
}

func ErrFromString(s string) (Err, error) {
	switch s {
	case "GateWayBadRequest":
		return Err_GateWayBadRequest, nil
	case "InteractionBadRequest":
		return Err_InteractionBadRequest, nil
	case "PaymentBadRequest":
		return Err_PaymentBadRequest, nil
	case "IMBadRequest":
		return Err_IMBadRequest, nil
	}
	return Err(0), fmt.Errorf("not a valid Err string")
}

func ErrPtr(v Err) *Err { return &v }
func (p *Err) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Err(result.Int64)
	return
}

func (p *Err) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
