// Code generated by thriftgo (0.2.3). DO NOT EDIT.

package payment

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/weedge/craftsman/cloudwego/common/kitex_gen/base"
	"strings"
)

type EventType int64

const (
	EventType_none         EventType = 0
	EventType_interactGift EventType = 1
	EventType_orderApple   EventType = 2
	EventType_orderWX      EventType = 3
	EventType_orderAlipay  EventType = 4
	EventType_orderDouyin  EventType = 5
)

func (p EventType) String() string {
	switch p {
	case EventType_none:
		return "none"
	case EventType_interactGift:
		return "interactGift"
	case EventType_orderApple:
		return "orderApple"
	case EventType_orderWX:
		return "orderWX"
	case EventType_orderAlipay:
		return "orderAlipay"
	case EventType_orderDouyin:
		return "orderDouyin"
	}
	return "<UNSET>"
}

func EventTypeFromString(s string) (EventType, error) {
	switch s {
	case "none":
		return EventType_none, nil
	case "interactGift":
		return EventType_interactGift, nil
	case "orderApple":
		return EventType_orderApple, nil
	case "orderWX":
		return EventType_orderWX, nil
	case "orderAlipay":
		return EventType_orderAlipay, nil
	case "orderDouyin":
		return EventType_orderDouyin, nil
	}
	return EventType(0), fmt.Errorf("not a valid EventType string")
}

func EventTypePtr(v EventType) *EventType { return &v }
func (p *EventType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EventType(result.Int64)
	return
}

func (p *EventType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BizType int64

const (
	BizType_none     BizType = 0
	BizType_live     BizType = 1
	BizType_recharge BizType = 2
)

func (p BizType) String() string {
	switch p {
	case BizType_none:
		return "none"
	case BizType_live:
		return "live"
	case BizType_recharge:
		return "recharge"
	}
	return "<UNSET>"
}

func BizTypeFromString(s string) (BizType, error) {
	switch s {
	case "none":
		return BizType_none, nil
	case "live":
		return BizType_live, nil
	case "recharge":
		return BizType_recharge, nil
	}
	return BizType(0), fmt.Errorf("not a valid BizType string")
}

func BizTypePtr(v BizType) *BizType { return &v }
func (p *BizType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BizType(result.Int64)
	return
}

func (p *BizType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AssetType int64

const (
	AssetType_none     AssetType = 0
	AssetType_goldCoin AssetType = 1
	AssetType_diamond  AssetType = 2
)

func (p AssetType) String() string {
	switch p {
	case AssetType_none:
		return "none"
	case AssetType_goldCoin:
		return "goldCoin"
	case AssetType_diamond:
		return "diamond"
	}
	return "<UNSET>"
}

func AssetTypeFromString(s string) (AssetType, error) {
	switch s {
	case "none":
		return AssetType_none, nil
	case "goldCoin":
		return AssetType_goldCoin, nil
	case "diamond":
		return AssetType_diamond, nil
	}
	return AssetType(0), fmt.Errorf("not a valid AssetType string")
}

func AssetTypePtr(v AssetType) *AssetType { return &v }
func (p *AssetType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AssetType(result.Int64)
	return
}

func (p *AssetType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BizAssetChangesReq struct {
	BizAssetChanges []*BizEventAssetChange `thrift:"bizAssetChanges,1,required" json:"bizAssetChanges"`
}

func NewBizAssetChangesReq() *BizAssetChangesReq {
	return &BizAssetChangesReq{}
}

func (p *BizAssetChangesReq) GetBizAssetChanges() (v []*BizEventAssetChange) {
	return p.BizAssetChanges
}
func (p *BizAssetChangesReq) SetBizAssetChanges(val []*BizEventAssetChange) {
	p.BizAssetChanges = val
}

var fieldIDToName_BizAssetChangesReq = map[int16]string{
	1: "bizAssetChanges",
}

func (p *BizAssetChangesReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBizAssetChanges bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBizAssetChanges = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBizAssetChanges {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BizAssetChangesReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_BizAssetChangesReq[fieldId]))
}

func (p *BizAssetChangesReq) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.BizAssetChanges = make([]*BizEventAssetChange, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewBizEventAssetChange()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.BizAssetChanges = append(p.BizAssetChanges, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *BizAssetChangesReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("BizAssetChangesReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BizAssetChangesReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bizAssetChanges", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.BizAssetChanges)); err != nil {
		return err
	}
	for _, v := range p.BizAssetChanges {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BizAssetChangesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizAssetChangesReq(%+v)", *p)
}

func (p *BizAssetChangesReq) DeepEqual(ano *BizAssetChangesReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.BizAssetChanges) {
		return false
	}
	return true
}

func (p *BizAssetChangesReq) Field1DeepEqual(src []*BizEventAssetChange) bool {

	if len(p.BizAssetChanges) != len(src) {
		return false
	}
	for i, v := range p.BizAssetChanges {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type BizEventAssetChange struct {
	EventId           string               `thrift:"eventId,1,required" json:"eventId"`
	OpUserId          int64                `thrift:"opUserId,2,required" json:"opUserId"`
	EventType         EventType            `thrift:"eventType,3,required" json:"eventType"`
	BizId             int64                `thrift:"bizId,4,required" json:"bizId"`
	BizType           BizType              `thrift:"bizType,5,required" json:"bizType"`
	ObjId             string               `thrift:"objId,6,required" json:"objId"`
	OpUserAssetChange *UserAssetChangeInfo `thrift:"opUserAssetChange,7,required" json:"opUserAssetChange"`
	ToUserAssetChange *UserAssetChangeInfo `thrift:"toUserAssetChange,8,required" json:"toUserAssetChange"`
}

func NewBizEventAssetChange() *BizEventAssetChange {
	return &BizEventAssetChange{}
}

func (p *BizEventAssetChange) GetEventId() (v string) {
	return p.EventId
}

func (p *BizEventAssetChange) GetOpUserId() (v int64) {
	return p.OpUserId
}

func (p *BizEventAssetChange) GetEventType() (v EventType) {
	return p.EventType
}

func (p *BizEventAssetChange) GetBizId() (v int64) {
	return p.BizId
}

func (p *BizEventAssetChange) GetBizType() (v BizType) {
	return p.BizType
}

func (p *BizEventAssetChange) GetObjId() (v string) {
	return p.ObjId
}

var BizEventAssetChange_OpUserAssetChange_DEFAULT *UserAssetChangeInfo

func (p *BizEventAssetChange) GetOpUserAssetChange() (v *UserAssetChangeInfo) {
	if !p.IsSetOpUserAssetChange() {
		return BizEventAssetChange_OpUserAssetChange_DEFAULT
	}
	return p.OpUserAssetChange
}

var BizEventAssetChange_ToUserAssetChange_DEFAULT *UserAssetChangeInfo

func (p *BizEventAssetChange) GetToUserAssetChange() (v *UserAssetChangeInfo) {
	if !p.IsSetToUserAssetChange() {
		return BizEventAssetChange_ToUserAssetChange_DEFAULT
	}
	return p.ToUserAssetChange
}
func (p *BizEventAssetChange) SetEventId(val string) {
	p.EventId = val
}
func (p *BizEventAssetChange) SetOpUserId(val int64) {
	p.OpUserId = val
}
func (p *BizEventAssetChange) SetEventType(val EventType) {
	p.EventType = val
}
func (p *BizEventAssetChange) SetBizId(val int64) {
	p.BizId = val
}
func (p *BizEventAssetChange) SetBizType(val BizType) {
	p.BizType = val
}
func (p *BizEventAssetChange) SetObjId(val string) {
	p.ObjId = val
}
func (p *BizEventAssetChange) SetOpUserAssetChange(val *UserAssetChangeInfo) {
	p.OpUserAssetChange = val
}
func (p *BizEventAssetChange) SetToUserAssetChange(val *UserAssetChangeInfo) {
	p.ToUserAssetChange = val
}

var fieldIDToName_BizEventAssetChange = map[int16]string{
	1: "eventId",
	2: "opUserId",
	3: "eventType",
	4: "bizId",
	5: "bizType",
	6: "objId",
	7: "opUserAssetChange",
	8: "toUserAssetChange",
}

func (p *BizEventAssetChange) IsSetOpUserAssetChange() bool {
	return p.OpUserAssetChange != nil
}

func (p *BizEventAssetChange) IsSetToUserAssetChange() bool {
	return p.ToUserAssetChange != nil
}

func (p *BizEventAssetChange) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetEventId bool = false
	var issetOpUserId bool = false
	var issetEventType bool = false
	var issetBizId bool = false
	var issetBizType bool = false
	var issetObjId bool = false
	var issetOpUserAssetChange bool = false
	var issetToUserAssetChange bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetEventId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetOpUserId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetEventType = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetBizId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
				issetBizType = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
				issetObjId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 7:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
				issetOpUserAssetChange = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 8:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
				issetToUserAssetChange = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetEventId {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetOpUserId {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetEventType {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetBizId {
		fieldId = 4
		goto RequiredFieldNotSetError
	}

	if !issetBizType {
		fieldId = 5
		goto RequiredFieldNotSetError
	}

	if !issetObjId {
		fieldId = 6
		goto RequiredFieldNotSetError
	}

	if !issetOpUserAssetChange {
		fieldId = 7
		goto RequiredFieldNotSetError
	}

	if !issetToUserAssetChange {
		fieldId = 8
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BizEventAssetChange[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_BizEventAssetChange[fieldId]))
}

func (p *BizEventAssetChange) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.EventId = v
	}
	return nil
}

func (p *BizEventAssetChange) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.OpUserId = v
	}
	return nil
}

func (p *BizEventAssetChange) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.EventType = EventType(v)
	}
	return nil
}

func (p *BizEventAssetChange) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.BizId = v
	}
	return nil
}

func (p *BizEventAssetChange) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.BizType = BizType(v)
	}
	return nil
}

func (p *BizEventAssetChange) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.ObjId = v
	}
	return nil
}

func (p *BizEventAssetChange) ReadField7(iprot thrift.TProtocol) error {
	p.OpUserAssetChange = NewUserAssetChangeInfo()
	if err := p.OpUserAssetChange.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *BizEventAssetChange) ReadField8(iprot thrift.TProtocol) error {
	p.ToUserAssetChange = NewUserAssetChangeInfo()
	if err := p.ToUserAssetChange.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *BizEventAssetChange) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("BizEventAssetChange"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BizEventAssetChange) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("eventId", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.EventId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("opUserId", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.OpUserId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("eventType", thrift.I32, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.EventType)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bizId", thrift.I64, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.BizId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField5(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bizType", thrift.I32, 5); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.BizType)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField6(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("objId", thrift.STRING, 6); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.ObjId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField7(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("opUserAssetChange", thrift.STRUCT, 7); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.OpUserAssetChange.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *BizEventAssetChange) writeField8(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("toUserAssetChange", thrift.STRUCT, 8); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.ToUserAssetChange.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *BizEventAssetChange) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizEventAssetChange(%+v)", *p)
}

func (p *BizEventAssetChange) DeepEqual(ano *BizEventAssetChange) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EventId) {
		return false
	}
	if !p.Field2DeepEqual(ano.OpUserId) {
		return false
	}
	if !p.Field3DeepEqual(ano.EventType) {
		return false
	}
	if !p.Field4DeepEqual(ano.BizId) {
		return false
	}
	if !p.Field5DeepEqual(ano.BizType) {
		return false
	}
	if !p.Field6DeepEqual(ano.ObjId) {
		return false
	}
	if !p.Field7DeepEqual(ano.OpUserAssetChange) {
		return false
	}
	if !p.Field8DeepEqual(ano.ToUserAssetChange) {
		return false
	}
	return true
}

func (p *BizEventAssetChange) Field1DeepEqual(src string) bool {

	if strings.Compare(p.EventId, src) != 0 {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field2DeepEqual(src int64) bool {

	if p.OpUserId != src {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field3DeepEqual(src EventType) bool {

	if p.EventType != src {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field4DeepEqual(src int64) bool {

	if p.BizId != src {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field5DeepEqual(src BizType) bool {

	if p.BizType != src {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field6DeepEqual(src string) bool {

	if strings.Compare(p.ObjId, src) != 0 {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field7DeepEqual(src *UserAssetChangeInfo) bool {

	if !p.OpUserAssetChange.DeepEqual(src) {
		return false
	}
	return true
}
func (p *BizEventAssetChange) Field8DeepEqual(src *UserAssetChangeInfo) bool {

	if !p.ToUserAssetChange.DeepEqual(src) {
		return false
	}
	return true
}

type UserAssetChangeInfo struct {
	UserId    int64     `thrift:"userId,1,required" json:"userId"`
	AssetType AssetType `thrift:"assetType,2,required" json:"assetType"`
	Incr      int32     `thrift:"incr,3,required" json:"incr"`
}

func NewUserAssetChangeInfo() *UserAssetChangeInfo {
	return &UserAssetChangeInfo{}
}

func (p *UserAssetChangeInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserAssetChangeInfo) GetAssetType() (v AssetType) {
	return p.AssetType
}

func (p *UserAssetChangeInfo) GetIncr() (v int32) {
	return p.Incr
}
func (p *UserAssetChangeInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserAssetChangeInfo) SetAssetType(val AssetType) {
	p.AssetType = val
}
func (p *UserAssetChangeInfo) SetIncr(val int32) {
	p.Incr = val
}

var fieldIDToName_UserAssetChangeInfo = map[int16]string{
	1: "userId",
	2: "assetType",
	3: "incr",
}

func (p *UserAssetChangeInfo) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetUserId bool = false
	var issetAssetType bool = false
	var issetIncr bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetUserId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetAssetType = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetIncr = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetUserId {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetAssetType {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetIncr {
		fieldId = 3
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_UserAssetChangeInfo[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_UserAssetChangeInfo[fieldId]))
}

func (p *UserAssetChangeInfo) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.UserId = v
	}
	return nil
}

func (p *UserAssetChangeInfo) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.AssetType = AssetType(v)
	}
	return nil
}

func (p *UserAssetChangeInfo) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Incr = v
	}
	return nil
}

func (p *UserAssetChangeInfo) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UserAssetChangeInfo"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *UserAssetChangeInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("userId", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.UserId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *UserAssetChangeInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("assetType", thrift.I32, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.AssetType)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *UserAssetChangeInfo) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("incr", thrift.I32, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(p.Incr); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *UserAssetChangeInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAssetChangeInfo(%+v)", *p)
}

func (p *UserAssetChangeInfo) DeepEqual(ano *UserAssetChangeInfo) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AssetType) {
		return false
	}
	if !p.Field3DeepEqual(ano.Incr) {
		return false
	}
	return true
}

func (p *UserAssetChangeInfo) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *UserAssetChangeInfo) Field2DeepEqual(src AssetType) bool {

	if p.AssetType != src {
		return false
	}
	return true
}
func (p *UserAssetChangeInfo) Field3DeepEqual(src int32) bool {

	if p.Incr != src {
		return false
	}
	return true
}

type BizAssetChangesResp struct {
	BizAssetChangeResList []*BizEventAssetChangerRes `thrift:"bizAssetChangeResList,1,required" json:"bizAssetChangeResList"`
	BizId                 int64                      `thrift:"bizId,2,required" json:"bizId"`
	BaseResp              *base.BaseResp             `thrift:"baseResp,255" json:"baseResp"`
}

func NewBizAssetChangesResp() *BizAssetChangesResp {
	return &BizAssetChangesResp{}
}

func (p *BizAssetChangesResp) GetBizAssetChangeResList() (v []*BizEventAssetChangerRes) {
	return p.BizAssetChangeResList
}

func (p *BizAssetChangesResp) GetBizId() (v int64) {
	return p.BizId
}

var BizAssetChangesResp_BaseResp_DEFAULT *base.BaseResp

func (p *BizAssetChangesResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return BizAssetChangesResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *BizAssetChangesResp) SetBizAssetChangeResList(val []*BizEventAssetChangerRes) {
	p.BizAssetChangeResList = val
}
func (p *BizAssetChangesResp) SetBizId(val int64) {
	p.BizId = val
}
func (p *BizAssetChangesResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

var fieldIDToName_BizAssetChangesResp = map[int16]string{
	1:   "bizAssetChangeResList",
	2:   "bizId",
	255: "baseResp",
}

func (p *BizAssetChangesResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BizAssetChangesResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBizAssetChangeResList bool = false
	var issetBizId bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBizAssetChangeResList = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetBizId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 255:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBizAssetChangeResList {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetBizId {
		fieldId = 2
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BizAssetChangesResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_BizAssetChangesResp[fieldId]))
}

func (p *BizAssetChangesResp) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.BizAssetChangeResList = make([]*BizEventAssetChangerRes, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewBizEventAssetChangerRes()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.BizAssetChangeResList = append(p.BizAssetChangeResList, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *BizAssetChangesResp) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.BizId = v
	}
	return nil
}

func (p *BizAssetChangesResp) ReadField255(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResp()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *BizAssetChangesResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("BizAssetChangesResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BizAssetChangesResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bizAssetChangeResList", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.BizAssetChangeResList)); err != nil {
		return err
	}
	for _, v := range p.BizAssetChangeResList {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BizAssetChangesResp) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bizId", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.BizId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *BizAssetChangesResp) writeField255(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("baseResp", thrift.STRUCT, 255); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *BizAssetChangesResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizAssetChangesResp(%+v)", *p)
}

func (p *BizAssetChangesResp) DeepEqual(ano *BizAssetChangesResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.BizAssetChangeResList) {
		return false
	}
	if !p.Field2DeepEqual(ano.BizId) {
		return false
	}
	if !p.Field255DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *BizAssetChangesResp) Field1DeepEqual(src []*BizEventAssetChangerRes) bool {

	if len(p.BizAssetChangeResList) != len(src) {
		return false
	}
	for i, v := range p.BizAssetChangeResList {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *BizAssetChangesResp) Field2DeepEqual(src int64) bool {

	if p.BizId != src {
		return false
	}
	return true
}
func (p *BizAssetChangesResp) Field255DeepEqual(src *base.BaseResp) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type BizEventAssetChangerRes struct {
	EventId     string     `thrift:"eventId,1,required" json:"eventId"`
	ChangeRes   bool       `thrift:"changeRes,2,required" json:"changeRes"`
	FailMsg     string     `thrift:"failMsg,3,required" json:"failMsg"`
	OpUserAsset *UserAsset `thrift:"opUserAsset,4,required" json:"opUserAsset"`
}

func NewBizEventAssetChangerRes() *BizEventAssetChangerRes {
	return &BizEventAssetChangerRes{}
}

func (p *BizEventAssetChangerRes) GetEventId() (v string) {
	return p.EventId
}

func (p *BizEventAssetChangerRes) GetChangeRes() (v bool) {
	return p.ChangeRes
}

func (p *BizEventAssetChangerRes) GetFailMsg() (v string) {
	return p.FailMsg
}

var BizEventAssetChangerRes_OpUserAsset_DEFAULT *UserAsset

func (p *BizEventAssetChangerRes) GetOpUserAsset() (v *UserAsset) {
	if !p.IsSetOpUserAsset() {
		return BizEventAssetChangerRes_OpUserAsset_DEFAULT
	}
	return p.OpUserAsset
}
func (p *BizEventAssetChangerRes) SetEventId(val string) {
	p.EventId = val
}
func (p *BizEventAssetChangerRes) SetChangeRes(val bool) {
	p.ChangeRes = val
}
func (p *BizEventAssetChangerRes) SetFailMsg(val string) {
	p.FailMsg = val
}
func (p *BizEventAssetChangerRes) SetOpUserAsset(val *UserAsset) {
	p.OpUserAsset = val
}

var fieldIDToName_BizEventAssetChangerRes = map[int16]string{
	1: "eventId",
	2: "changeRes",
	3: "failMsg",
	4: "opUserAsset",
}

func (p *BizEventAssetChangerRes) IsSetOpUserAsset() bool {
	return p.OpUserAsset != nil
}

func (p *BizEventAssetChangerRes) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetEventId bool = false
	var issetChangeRes bool = false
	var issetFailMsg bool = false
	var issetOpUserAsset bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetEventId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetChangeRes = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetFailMsg = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 4:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetOpUserAsset = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetEventId {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetChangeRes {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetFailMsg {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetOpUserAsset {
		fieldId = 4
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BizEventAssetChangerRes[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_BizEventAssetChangerRes[fieldId]))
}

func (p *BizEventAssetChangerRes) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.EventId = v
	}
	return nil
}

func (p *BizEventAssetChangerRes) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		p.ChangeRes = v
	}
	return nil
}

func (p *BizEventAssetChangerRes) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FailMsg = v
	}
	return nil
}

func (p *BizEventAssetChangerRes) ReadField4(iprot thrift.TProtocol) error {
	p.OpUserAsset = NewUserAsset()
	if err := p.OpUserAsset.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *BizEventAssetChangerRes) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("BizEventAssetChangerRes"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BizEventAssetChangerRes) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("eventId", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.EventId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BizEventAssetChangerRes) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("changeRes", thrift.BOOL, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteBool(p.ChangeRes); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *BizEventAssetChangerRes) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("failMsg", thrift.STRING, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FailMsg); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *BizEventAssetChangerRes) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("opUserAsset", thrift.STRUCT, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.OpUserAsset.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *BizEventAssetChangerRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizEventAssetChangerRes(%+v)", *p)
}

func (p *BizEventAssetChangerRes) DeepEqual(ano *BizEventAssetChangerRes) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EventId) {
		return false
	}
	if !p.Field2DeepEqual(ano.ChangeRes) {
		return false
	}
	if !p.Field3DeepEqual(ano.FailMsg) {
		return false
	}
	if !p.Field4DeepEqual(ano.OpUserAsset) {
		return false
	}
	return true
}

func (p *BizEventAssetChangerRes) Field1DeepEqual(src string) bool {

	if strings.Compare(p.EventId, src) != 0 {
		return false
	}
	return true
}
func (p *BizEventAssetChangerRes) Field2DeepEqual(src bool) bool {

	if p.ChangeRes != src {
		return false
	}
	return true
}
func (p *BizEventAssetChangerRes) Field3DeepEqual(src string) bool {

	if strings.Compare(p.FailMsg, src) != 0 {
		return false
	}
	return true
}
func (p *BizEventAssetChangerRes) Field4DeepEqual(src *UserAsset) bool {

	if !p.OpUserAsset.DeepEqual(src) {
		return false
	}
	return true
}

type UserAsset struct {
	UserId    int64     `thrift:"userId,1,required" json:"userId"`
	AssetType AssetType `thrift:"assetType,2,required" json:"assetType"`
	AssetCn   int32     `thrift:"assetCn,3,required" json:"assetCn"`
}

func NewUserAsset() *UserAsset {
	return &UserAsset{}
}

func (p *UserAsset) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserAsset) GetAssetType() (v AssetType) {
	return p.AssetType
}

func (p *UserAsset) GetAssetCn() (v int32) {
	return p.AssetCn
}
func (p *UserAsset) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserAsset) SetAssetType(val AssetType) {
	p.AssetType = val
}
func (p *UserAsset) SetAssetCn(val int32) {
	p.AssetCn = val
}

var fieldIDToName_UserAsset = map[int16]string{
	1: "userId",
	2: "assetType",
	3: "assetCn",
}

func (p *UserAsset) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetUserId bool = false
	var issetAssetType bool = false
	var issetAssetCn bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetUserId = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetAssetType = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetAssetCn = true
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetUserId {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetAssetType {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetAssetCn {
		fieldId = 3
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_UserAsset[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_UserAsset[fieldId]))
}

func (p *UserAsset) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.UserId = v
	}
	return nil
}

func (p *UserAsset) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.AssetType = AssetType(v)
	}
	return nil
}

func (p *UserAsset) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.AssetCn = v
	}
	return nil
}

func (p *UserAsset) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UserAsset"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *UserAsset) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("userId", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.UserId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *UserAsset) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("assetType", thrift.I32, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.AssetType)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *UserAsset) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("assetCn", thrift.I32, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(p.AssetCn); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *UserAsset) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAsset(%+v)", *p)
}

func (p *UserAsset) DeepEqual(ano *UserAsset) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UserId) {
		return false
	}
	if !p.Field2DeepEqual(ano.AssetType) {
		return false
	}
	if !p.Field3DeepEqual(ano.AssetCn) {
		return false
	}
	return true
}

func (p *UserAsset) Field1DeepEqual(src int64) bool {

	if p.UserId != src {
		return false
	}
	return true
}
func (p *UserAsset) Field2DeepEqual(src AssetType) bool {

	if p.AssetType != src {
		return false
	}
	return true
}
func (p *UserAsset) Field3DeepEqual(src int32) bool {

	if p.AssetCn != src {
		return false
	}
	return true
}
