// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAssertRecord = "user_assert_record"

// UserAssertRecord mapped from table <user_assert_record>
type UserAssertRecord struct {
	RecordID  int64     `gorm:"column:recordId;type:bigint unsigned;primaryKey;autoIncrement:true" json:"recordId"`
	OpUserID  int64     `gorm:"column:opUserId;type:bigint unsigned;not null" json:"opUserId"`
	ToUserID  int64     `gorm:"column:toUserId;type:bigint unsigned;not null" json:"toUserId"`
	BizID     int64     `gorm:"column:bizId;type:bigint unsigned;not null" json:"bizId"`
	BizType   int32     `gorm:"column:bizType;type:tinyint unsigned;not null" json:"bizType"`
	ObjID     string    `gorm:"column:objId;type:varchar(128);not null" json:"objId"`
	EventID   string    `gorm:"column:eventId;type:varchar(128);not null" json:"eventId"`
	EventType string    `gorm:"column:eventType;type:varchar(128);not null" json:"eventType"`
	Record    string    `gorm:"column:record;type:varchar(256);not null" json:"record"`
	RecordOp  string    `gorm:"column:recordOp;type:varchar(64);not null" json:"recordOp"`
	CreatedAt time.Time `gorm:"column:createdAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName UserAssertRecord's table name
func (*UserAssertRecord) TableName() string {
	return TableNameUserAssertRecord
}
