// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAsset = "user_asset"

// UserAsset mapped from table <user_asset>
type UserAsset struct {
	UserID    int64     `gorm:"column:userId;type:bigint unsigned;primaryKey" json:"userId"`
	AssetCn   int64     `gorm:"column:assetCn;type:bigint unsigned;not null" json:"assetCn"`
	AssetType int32     `gorm:"column:assetType;type:tinyint unsigned;primaryKey" json:"assetType"`
	Version   int64     `gorm:"column:version;type:bigint unsigned;not null" json:"version"`
	CreatedAt time.Time `gorm:"column:createdAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName UserAsset's table name
func (*UserAsset) TableName() string {
	return TableNameUserAsset
}
