// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAssetRecord = "user_asset_record"

// UserAssetRecord mapped from table <user_asset_record>
type UserAssetRecord struct {
	UserID     int64     `gorm:"column:userId;type:bigint unsigned;primaryKey" json:"userId"`
	OpUserType int32     `gorm:"column:opUserType;type:tinyint unsigned;primaryKey" json:"opUserType"`
	BizID      int64     `gorm:"column:bizId;type:bigint unsigned;not null" json:"bizId"`
	BizType    int32     `gorm:"column:bizType;type:tinyint unsigned;not null" json:"bizType"`
	ObjID      string    `gorm:"column:objId;type:varchar(128);not null" json:"objId"`
	EventID    string    `gorm:"column:eventId;type:varchar(128);primaryKey" json:"eventId"`
	EventType  string    `gorm:"column:eventType;type:varchar(128);not null" json:"eventType"`
	Record     string    `gorm:"column:record;type:varchar(256);not null" json:"record"`
	RecordOp   string    `gorm:"column:recordOp;type:varchar(64);not null" json:"recordOp"`
	CreatedAt  time.Time `gorm:"column:createdAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName UserAssetRecord's table name
func (*UserAssetRecord) TableName() string {
	return TableNameUserAssetRecord
}
